name: "Prueba #1"
run-name: "Prueba #1"

on:
  workflow_dispatch:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: winespaapi
          MYSQL_USER: wine
          MYSQL_PASSWORD: tech
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OS packages for mysqlclient
        run: |
          sudo apt-get update
          sudo apt-get install -y default-libmysqlclient-dev build-essential

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show Django version
        run: |
          python -c "import django; print('Django version:', django.get_version())"
        env:
          DJANGO_SETTINGS_MODULE: winespa.settings
          PYTHONPATH: ${{ github.workspace }}
          DB_NAME: winespaapi
          DB_USER: wine
          DB_PASSWORD: tech
          DB_HOST: 127.0.0.1
          DB_PORT: 3306

      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P3306 --silent; do
            echo "Waiting for MySQL..."
            sleep 2
          done
          echo "MySQL is up"

      - name: Configure database permissions
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -proot -e "
          GRANT ALL PRIVILEGES ON *.* TO 'wine'@'%' WITH GRANT OPTION;
          FLUSH PRIVILEGES;
          CREATE DATABASE IF NOT EXISTS test_winespaapi;
          GRANT ALL PRIVILEGES ON test_winespaapi.* TO 'wine'@'%';
          FLUSH PRIVILEGES;"

      - name: Verify test database
        run: |
          mysql -h 127.0.0.1 -P 3306 -u wine -ptech -e "SHOW DATABASES;"
          echo "Test database configured correctly"

      - name: Run tests
        run: |
          pytest -v
        env:
          DJANGO_SETTINGS_MODULE: winespa.settings
          PYTHONPATH: ${{ github.workspace }}
          DEBUG: "True"
          DB_NAME: winespaapi
          DB_USER: wine
          DB_PASSWORD: tech
          DB_HOST: 127.0.0.1
          DB_PORT: 3306


